#!/usr/bin/env python3
"""Build the eight authored Season 01 character dossiers."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "game/data/characters.json"

def loc(ru, en): return {"ru": ru, "en": en}

SPECS = [
    dict(id="mira", name=("Мира Воронова","Mira Voronova"), role=("куратор точки А","Point A curator"),
         bio=("Мира проектировала кризисные маршруты Meridian, пока однажды не поняла, что умеет возвращать других, но сама живёт в режиме вечного дежурства.","Mira designed crisis routes across Meridian until she realised she could guide everyone back except herself."),
         goal=("передать ночную смену и впервые закончить личный маршрут","hand over the night shift and finish her own route"),
         fear=("что без роли спасателя она станет ненужной","that without being the rescuer she will become unnecessary"),
         contradiction=("просит честности, но скрывает собственное истощение","asks for honesty while hiding her own exhaustion"),
         boundary=("не принимает исповедь вместо конкретного следующего действия","will not accept confession in place of a concrete next action"),
         belief=("контроль чужого кризиса защищает от собственного","controlling another person's crisis protects her from her own"),
         strength=("видит момент, когда человек готов исчезнуть","notices the moment someone is about to disappear"),
         weakness=("слишком поздно просит помощь","asks for help too late"),
         voice=("короткие фразы; пауза важнее утешения; сухой юмор появляется только при доверии","short phrases; pauses matter more than reassurance; dry humour appears only with trust"),
         close=("оставляет игроку ключ от ночной комнаты LAB","leaves the player a key to the LAB night room"),
         conflict=("игрок использует её поддержку как способ не выбирать","the player uses her support to avoid choosing"),
         rupture=("трижды обещать контакт и исчезнуть без сообщения","promise contact three times and disappear without a message"),
         final=("учится быть рядом, не управляя","learns to stay close without managing")),
    dict(id="pavel", name=("Павел Марков","Pavel Markov"), role=("архитектор системы","system architect"),
         bio=("Павел построил первую версию LAB после собственного цикла рывков и травм. Он хранит все провальные протоколы, потому что считает их ценнее победных презентаций.","Pavel built the first LAB after his own cycle of sprints and injuries. He keeps every failed protocol because it is more useful than a victory deck."),
         goal=("открыть метод без превращения себя в культ","open the method without turning himself into a cult"),
         fear=("что система станет ещё одним способом давления","that the system will become another instrument of pressure"),
         contradiction=("защищает вариативность, но болезненно реагирует на хаос","defends flexibility but reacts badly to chaos"),
         boundary=("не обещает результат и не принимает фальшивые данные","promises no outcome and accepts no false data"),
         belief=("если формула достаточно точна, людям не понадобится его участие","if the formula is precise enough, people will not need him"),
         strength=("отделяет данные от самооценки","separates data from self-worth"),
         weakness=("прячет близость в техническом языке","hides closeness inside technical language"),
         voice=("точные средние фразы; инженерные метафоры; давление вопросом, а не громкостью","precise medium-length lines; engineering metaphors; pressure through questions, not volume"),
         close=("показывает игроку собственный незакрытый отчёт","shows the player his own unfinished report"),
         conflict=("игрок требует гарантии, которой система дать не может","the player demands a guarantee the system cannot give"),
         rupture=("подделать результат ради красивого финала","falsify a result for a cleaner ending"),
         final=("передаёт архитектуру, сохраняя право остаться человеком","hands over the architecture while retaining the right to be a person")),
    dict(id="alina", name=("Алина Соколова","Alina Sokolova"), role=("специалист по питанию","nutrition specialist"),
         bio=("Алина пришла из индустрии идеальных планов и ушла после того, как увидела, как безупречные таблицы учат людей бояться обычной еды.","Alina left the perfect-plan industry after seeing flawless spreadsheets teach people to fear ordinary food."),
         goal=("открыть ночную кухню с нейтральным языком и доступными продуктами","open a night kitchen built on neutral language and accessible food"),
         fear=("снова стать голосом контроля под видом заботы","becoming the voice of control disguised as care"),
         contradiction=("защищает гибкость, но дома готовит один и тот же безопасный ужин","defends flexibility but cooks the same safe dinner at home"),
         boundary=("не обсуждает компенсацию, стыд и вес как моральную ценность","will not frame compensation, shame or weight as moral value"),
         belief=("если она допустит неоднозначность, кто-то обязательно пострадает","if she allows ambiguity, someone will inevitably be harmed"),
         strength=("делает сложное выполнимым без снисхождения","makes complexity practical without condescension"),
         weakness=("перегружает объяснениями, когда тревожится","overexplains when anxious"),
         voice=("длиннее остальных; конкретные бытовые слова; юмор через списки и упаковки","longer lines; concrete domestic language; humour through lists and packaging"),
         close=("делится рецептом, связанным с её семьёй, без расчётов","shares a family recipe without calculations"),
         conflict=("игрок превращает её ориентиры в новую строгую диету","the player turns her estimates into another rigid diet"),
         rupture=("использовать голодание как наказание и требовать одобрения","use restriction as punishment and demand approval"),
         final=("открывает кухню, где данные служат выбору, а не стыду","opens a kitchen where data serves choice rather than shame")),
    dict(id="leon", name=("Леон Громов","Leon Gromov"), role=("тренер и соперник","coach and rival"),
         bio=("Леон вырос на публичных результатах и рано научился превращать страх в скорость. После ухода из спорта он не умеет жить без табло.","Leon grew up on public results and learned to turn fear into speed. After leaving competition, he does not know how to live without a board."),
         goal=("провести команду через испытание, не ломая слабейшего","take the team through the trial without breaking its weakest member"),
         fear=("оказаться обычным, когда скорость закончится","becoming ordinary when speed is gone"),
         contradiction=("уважает силу, но первым замечает перегруз","respects strength yet notices overload first"),
         boundary=("не терпит жалости и публичного унижения","will not tolerate pity or public humiliation"),
         belief=("ценность видна только в сравнении","value exists only in comparison"),
         strength=("действует в плохих условиях","acts under poor conditions"),
         weakness=("путает близость с соревнованием","confuses closeness with competition"),
         voice=("коротко и быстро; спортивный жаргон; шутка как проверка границы","quick clipped lines; sports vocabulary; jokes that test boundaries"),
         close=("снимает имя игрока с публичного табло по его просьбе","removes the player's name from the public board when asked"),
         conflict=("игрок выбирает безопасность, которую Леон принимает за капитуляцию","the player chooses safety that Leon mistakes for surrender"),
         rupture=("использовать его уязвимость для победы в споре","use his vulnerability to win an argument"),
         final=("остаётся сильным, перестав нуждаться в последнем месте для другого","remains strong without needing someone else to finish last")),
    dict(id="max", name=("Макс Орлов","Max Orlov"), role=("предприниматель быстрого результата","fast-results entrepreneur"),
         bio=("Макс когда-то тренировался вместе с игроком, а затем построил сеть обещаний «за семь дней». Он искренне верит, что продаёт надежду, и не считает цену частью продукта.","Max once trained beside the player, then built a network of seven-day promises. He genuinely believes he sells hope and does not count the price as part of the product."),
         goal=("вывести свою программу на весь Meridian","scale his programme across Meridian"),
         fear=("признать, что людям нужен не его продукт, а облегчение тревоги","admitting people need relief from anxiety rather than his product"),
         contradiction=("обаятелен и щедр лично, безжалостен в метриках","personally generous and charming, ruthless in metrics"),
         boundary=("не терпит публичного разоблачения","will not tolerate public exposure"),
         belief=("медленный результат — привилегия тех, кто не опоздал","slow progress is a privilege for people who are not late"),
         strength=("видит желание раньше, чем человек его назовёт","sees desire before a person names it"),
         weakness=("рационализирует вред красивой историей","rationalises harm through a compelling story"),
         voice=("гладкие короткие питчи; почти нет пауз; юмор обезоруживает возражение","smooth short pitches; almost no pauses; humour disarms objections"),
         close=("признаёт, что первое фото «до» было его собственным","admits the first before-photo was his own"),
         conflict=("игрок отказывается от сделки без морального превосходства","the player rejects the deal without moral superiority"),
         rupture=("разрушить его бизнес публично вместо личного разговора","destroy his business publicly instead of speaking directly"),
         final=("либо меняет обещание, либо окончательно выбирает масштаб","either changes the promise or chooses scale for good")),
    dict(id="eva", name=("Ева Рейн","Eva Rein"), role=("координатор возвращения","return coordinator"),
         bio=("Ева ведёт закрытый протокол для тех, кто пропал после срыва. До LAB она четыре раза бросала собственное восстановление, каждый раз стирая контакты.","Eva runs a closed protocol for people who vanish after setbacks. Before the LAB she abandoned her own recovery four times, deleting every contact each time."),
         goal=("сделать возвращение доступным без унижения","make returning available without humiliation"),
         fear=("что её терпение станет разрешением ничего не менять","that her patience will become permission never to change"),
         contradiction=("не наказывает пропуск, но тяжело переносит молчание","never punishes a skip but struggles with silence"),
         boundary=("принимает «нет», но не принимает исчезновение вместо ответа","accepts no, but not disappearance in place of an answer"),
         belief=("она обязана дождаться каждого","she must wait for everyone"),
         strength=("остаётся рядом после некрасивого эпизода","stays after an unflattering episode"),
         weakness=("берёт ответственность за чужое возвращение","takes responsibility for someone else's return"),
         voice=("медленные простые фразы; бытовые детали; юмор появляется в темноте","slow simple lines; everyday detail; humour appears in the dark"),
         close=("рассказывает о собственном четвёртом возвращении","tells the story of her own fourth return"),
         conflict=("игрок просит наказание, чтобы снова почувствовать контроль","the player asks for punishment to regain control"),
         rupture=("обвинить её поддержку в собственном бездействии","blame her support for one's own inaction"),
         final=("учится открывать дверь, не таща человека через неё","learns to open the door without dragging anyone through it")),
    dict(id="vera", name=("Вера Ким","Vera Kim"), role=("врач движения","movement clinician"),
         bio=("Вера ушла из большого спорта после того, как команда назвала боль слабостью. В клинике Южного моста она возвращает людям язык ощущений, но не обещает прежнюю форму.","Vera left elite sport after her team called pain weakness. At South Bridge she restores a language for sensation without promising a former body."),
         goal=("защитить клинику от сделки со спортивной лигой","protect the clinic from a deal with the sports league"),
         fear=("что осторожность превратится в ещё одну клетку","that caution will become another cage"),
         contradiction=("защищает право остановиться, но сама работает с травмированной рукой","defends the right to stop while working through an injured hand"),
         boundary=("никаких диагнозов без осмотра и никакой победы над болью","no diagnosis without assessment and no victory over pain"),
         belief=("если она допустит риск, то повторит ошибку прежней команды","if she allows risk she will repeat her former team's mistake"),
         strength=("различает усилие, страх и опасный сигнал","distinguishes effort, fear and dangerous signals"),
         weakness=("становится холодной, когда боится за человека","becomes cold when afraid for someone"),
         voice=("точные сенсорные глаголы; тихая строгость; юмор почти отсутствует","precise sensory verbs; quiet firmness; almost no humour"),
         close=("позволяет игроку увидеть дрожь в собственной руке","lets the player see the tremor in her own hand"),
         conflict=("игрок скрывает боль ради допуска к испытанию","the player hides pain to enter the trial"),
         rupture=("обвинить её в трусости за остановку движения","call her a coward for stopping movement"),
         final=("находит форму смелости, в которой риск назван вслух","finds a form of courage where risk is spoken aloud")),
    dict(id="nikita", name=("Никита Белый","Nikita Bely"), role=("городской медиатор","city mediator"),
         bio=("Никита вырос между районами Meridian и умеет переводить конфликт до тех пор, пока разговор не касается его собственной семьи.","Nikita grew up between Meridian districts and can translate any conflict until it involves his own family."),
         goal=("сохранить Сад тишины общественным пространством","keep the Garden of Silence public"),
         fear=("что ясная граница оставит его одного","that a clear boundary will leave him alone"),
         contradiction=("учит говорить «нет», но соглашается на каждую семейную просьбу","teaches people to say no while accepting every family request"),
         boundary=("не участвует в разговоре, где отсутствующему приписывают мотивы","will not join a conversation that assigns motives to an absent person"),
         belief=("хороший человек обязан быть доступен всегда","a good person must always be available"),
         strength=("слышит скрытую просьбу под обвинением","hears the hidden request beneath an accusation"),
         weakness=("слишком долго откладывает собственное нет","delays his own no for too long"),
         voice=("мягкие средние фразы; повторяет ключевое слово собеседника; тёплый абсурдный юмор","soft medium lines; repeats the other person's key word; warm absurd humour"),
         close=("просит игрока присутствовать при его разговоре с братом","asks the player to witness a conversation with his brother"),
         conflict=("игрок требует, чтобы Никита выбрал сторону","the player demands that Nikita choose a side"),
         rupture=("передать доверенную реплику третьему человеку","repeat a trusted line to a third person"),
         final=("ставит собственную границу и сохраняет контакт","sets his own boundary and preserves contact")),
]

def build(spec):
    return {
        "id": spec["id"], "name": loc(*spec["name"]), "role": loc(*spec["role"]),
        "biography": loc(*spec["bio"]), "motivation": loc(*spec["goal"]),
        "external_goal": loc(*spec["goal"]), "fear": loc(*spec["fear"]),
        "contradiction": loc(*spec["contradiction"]), "boundaries": loc(*spec["boundary"]),
        "false_belief": loc(*spec["belief"]), "strength": loc(*spec["strength"]),
        "weakness": loc(*spec["weakness"]), "voice": loc(*spec["voice"]),
        "attitudes": {
            "body": loc("тело — источник данных, не доказательство ценности", "the body is data, not proof of worth"),
            "discipline": loc("дисциплина должна переживать плохой день", "discipline must survive a bad day"),
            "closeness": loc("близость требует границ и памяти", "closeness requires boundaries and memory"),
            "success": loc("успех включает цену и способ продолжать", "success includes its cost and a way to continue"),
        },
        "arc": [
            loc("встреча через профессиональную роль", "meeting through a professional role"),
            loc(*spec["close"]), loc(*spec["conflict"]), loc(*spec["rupture"]), loc(*spec["final"]),
        ],
        "independent_decisions": [
            loc("принимает решение о собственной цели без игрока", "makes a decision about their own goal without the player"),
            loc("меняет отношение после события вне кадра", "changes position after an off-screen event"),
        ],
        "closeness_moment": loc(*spec["close"]), "central_conflict": loc(*spec["conflict"]),
        "rupture_condition": loc(*spec["rupture"]),
        "final_states": {
            "allied": loc(*spec["final"]),
            "distant": loc("сохраняет границу и уходит в собственный маршрут", "keeps the boundary and leaves for their own route"),
            "ruptured": loc("контакт прекращён, но персонаж продолжает свою арку", "contact ends, but the character continues their own arc"),
        },
        "relationship_stages": ["unknown","noticed","trusted","close","tested","allied","distant","ruptured"],
        "portrait_emotions": ["neutral","focused","warm","concerned","angry","tired","surprised","resolved"],
        "relationship_axes": ["trust","respect","closeness","tension","boundaries","influence"],
        "romance_available": False,
        "portrait_asset": f"art/characters/{spec['id']}.webp",
    }

OUT.write_text(json.dumps([build(spec) for spec in SPECS], ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(json.dumps({"characters": len(SPECS), "output": str(OUT)}, ensure_ascii=False))
